// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repositories "github.com/alexbro4u/gotemplate/internal/layers/repositories"
	mock "github.com/stretchr/testify/mock"

	transaction "github.com/alexbro4u/gotemplate/internal/layers/repositories/transaction"
)

// MockUserGroupRepository is an autogenerated mock type for the UserGroupRepository type
type MockUserGroupRepository struct {
	mock.Mock
}

type MockUserGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserGroupRepository) EXPECT() *MockUserGroupRepository_Expecter {
	return &MockUserGroupRepository_Expecter{mock: &_m.Mock}
}

// AddUserToGroup provides a mock function with given fields: ctx, userID, groupName
func (_m *MockUserGroupRepository) AddUserToGroup(ctx context.Context, userID int64, groupName string) error {
	ret := _m.Called(ctx, userID, groupName)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, userID, groupName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserGroupRepository_AddUserToGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToGroup'
type MockUserGroupRepository_AddUserToGroup_Call struct {
	*mock.Call
}

// AddUserToGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - groupName string
func (_e *MockUserGroupRepository_Expecter) AddUserToGroup(ctx interface{}, userID interface{}, groupName interface{}) *MockUserGroupRepository_AddUserToGroup_Call {
	return &MockUserGroupRepository_AddUserToGroup_Call{Call: _e.mock.On("AddUserToGroup", ctx, userID, groupName)}
}

func (_c *MockUserGroupRepository_AddUserToGroup_Call) Run(run func(ctx context.Context, userID int64, groupName string)) *MockUserGroupRepository_AddUserToGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MockUserGroupRepository_AddUserToGroup_Call) Return(_a0 error) *MockUserGroupRepository_AddUserToGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserGroupRepository_AddUserToGroup_Call) RunAndReturn(run func(context.Context, int64, string) error) *MockUserGroupRepository_AddUserToGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupNamesByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserGroupRepository) GetGroupNamesByUserID(ctx context.Context, userID int64) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupNamesByUserID")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserGroupRepository_GetGroupNamesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupNamesByUserID'
type MockUserGroupRepository_GetGroupNamesByUserID_Call struct {
	*mock.Call
}

// GetGroupNamesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockUserGroupRepository_Expecter) GetGroupNamesByUserID(ctx interface{}, userID interface{}) *MockUserGroupRepository_GetGroupNamesByUserID_Call {
	return &MockUserGroupRepository_GetGroupNamesByUserID_Call{Call: _e.mock.On("GetGroupNamesByUserID", ctx, userID)}
}

func (_c *MockUserGroupRepository_GetGroupNamesByUserID_Call) Run(run func(ctx context.Context, userID int64)) *MockUserGroupRepository_GetGroupNamesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserGroupRepository_GetGroupNamesByUserID_Call) Return(_a0 []string, _a1 error) *MockUserGroupRepository_GetGroupNamesByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserGroupRepository_GetGroupNamesByUserID_Call) RunAndReturn(run func(context.Context, int64) ([]string, error)) *MockUserGroupRepository_GetGroupNamesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// WithExecutor provides a mock function with given fields: exec
func (_m *MockUserGroupRepository) WithExecutor(exec transaction.SqlxTx) repositories.UserGroupRepository {
	ret := _m.Called(exec)

	if len(ret) == 0 {
		panic("no return value specified for WithExecutor")
	}

	var r0 repositories.UserGroupRepository
	if rf, ok := ret.Get(0).(func(transaction.SqlxTx) repositories.UserGroupRepository); ok {
		r0 = rf(exec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.UserGroupRepository)
		}
	}

	return r0
}

// MockUserGroupRepository_WithExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithExecutor'
type MockUserGroupRepository_WithExecutor_Call struct {
	*mock.Call
}

// WithExecutor is a helper method to define mock.On call
//   - exec transaction.SqlxTx
func (_e *MockUserGroupRepository_Expecter) WithExecutor(exec interface{}) *MockUserGroupRepository_WithExecutor_Call {
	return &MockUserGroupRepository_WithExecutor_Call{Call: _e.mock.On("WithExecutor", exec)}
}

func (_c *MockUserGroupRepository_WithExecutor_Call) Run(run func(exec transaction.SqlxTx)) *MockUserGroupRepository_WithExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(transaction.SqlxTx))
	})
	return _c
}

func (_c *MockUserGroupRepository_WithExecutor_Call) Return(_a0 repositories.UserGroupRepository) *MockUserGroupRepository_WithExecutor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserGroupRepository_WithExecutor_Call) RunAndReturn(run func(transaction.SqlxTx) repositories.UserGroupRepository) *MockUserGroupRepository_WithExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserGroupRepository creates a new instance of MockUserGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserGroupRepository {
	mock := &MockUserGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
