// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/alexbro4u/gotemplate/internal/dto/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockPasswordResetRepository is an autogenerated mock type for the PasswordResetRepository type
type MockPasswordResetRepository struct {
	mock.Mock
}

type MockPasswordResetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordResetRepository) EXPECT() *MockPasswordResetRepository_Expecter {
	return &MockPasswordResetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockPasswordResetRepository) Create(ctx context.Context, in repository.CreatePasswordResetInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreatePasswordResetInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPasswordResetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.CreatePasswordResetInput
func (_e *MockPasswordResetRepository_Expecter) Create(ctx interface{}, in interface{}) *MockPasswordResetRepository_Create_Call {
	return &MockPasswordResetRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockPasswordResetRepository_Create_Call) Run(run func(ctx context.Context, in repository.CreatePasswordResetInput)) *MockPasswordResetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreatePasswordResetInput))
	})
	return _c
}

func (_c *MockPasswordResetRepository_Create_Call) Return(_a0 error) *MockPasswordResetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreatePasswordResetInput) error) *MockPasswordResetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, in
func (_m *MockPasswordResetRepository) Get(ctx context.Context, in repository.GetPasswordResetInput) (*repository.GetPasswordResetOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.GetPasswordResetOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetPasswordResetInput) (*repository.GetPasswordResetOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetPasswordResetInput) *repository.GetPasswordResetOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.GetPasswordResetOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetPasswordResetInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordResetRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPasswordResetRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.GetPasswordResetInput
func (_e *MockPasswordResetRepository_Expecter) Get(ctx interface{}, in interface{}) *MockPasswordResetRepository_Get_Call {
	return &MockPasswordResetRepository_Get_Call{Call: _e.mock.On("Get", ctx, in)}
}

func (_c *MockPasswordResetRepository_Get_Call) Run(run func(ctx context.Context, in repository.GetPasswordResetInput)) *MockPasswordResetRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.GetPasswordResetInput))
	})
	return _c
}

func (_c *MockPasswordResetRepository_Get_Call) Return(_a0 *repository.GetPasswordResetOutput, _a1 error) *MockPasswordResetRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordResetRepository_Get_Call) RunAndReturn(run func(context.Context, repository.GetPasswordResetInput) (*repository.GetPasswordResetOutput, error)) *MockPasswordResetRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function with given fields: ctx, in
func (_m *MockPasswordResetRepository) MarkUsed(ctx context.Context, in repository.MarkPasswordResetUsedInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.MarkPasswordResetUsedInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockPasswordResetRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.MarkPasswordResetUsedInput
func (_e *MockPasswordResetRepository_Expecter) MarkUsed(ctx interface{}, in interface{}) *MockPasswordResetRepository_MarkUsed_Call {
	return &MockPasswordResetRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, in)}
}

func (_c *MockPasswordResetRepository_MarkUsed_Call) Run(run func(ctx context.Context, in repository.MarkPasswordResetUsedInput)) *MockPasswordResetRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.MarkPasswordResetUsedInput))
	})
	return _c
}

func (_c *MockPasswordResetRepository_MarkUsed_Call) Return(_a0 error) *MockPasswordResetRepository_MarkUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetRepository_MarkUsed_Call) RunAndReturn(run func(context.Context, repository.MarkPasswordResetUsedInput) error) *MockPasswordResetRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *MockPasswordResetRepository) DeleteExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordResetRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockPasswordResetRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPasswordResetRepository_Expecter) DeleteExpired(ctx interface{}) *MockPasswordResetRepository_DeleteExpired_Call {
	return &MockPasswordResetRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *MockPasswordResetRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *MockPasswordResetRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPasswordResetRepository_DeleteExpired_Call) Return(_a0 error) *MockPasswordResetRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordResetRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) error) *MockPasswordResetRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordResetRepository creates a new instance of MockPasswordResetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordResetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordResetRepository {
	mock := &MockPasswordResetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
