// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repositories "github.com/alexbro4u/gotemplate/internal/layers/repositories"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/alexbro4u/gotemplate/internal/dto/repository"

	transaction "github.com/alexbro4u/gotemplate/internal/layers/repositories/transaction"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockUserRepository) Create(ctx context.Context, in repository.CreateUserInput) (*repository.CreateUserOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *repository.CreateUserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserInput) (*repository.CreateUserOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.CreateUserInput) *repository.CreateUserOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.CreateUserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.CreateUserInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.CreateUserInput
func (_e *MockUserRepository_Expecter) Create(ctx interface{}, in interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(ctx context.Context, in repository.CreateUserInput)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.CreateUserInput))
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(_a0 *repository.CreateUserOutput, _a1 error) *MockUserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context.Context, repository.CreateUserInput) (*repository.CreateUserOutput, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, in
func (_m *MockUserRepository) Delete(ctx context.Context, in repository.DeleteUserInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.DeleteUserInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.DeleteUserInput
func (_e *MockUserRepository_Expecter) Delete(ctx interface{}, in interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, in)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(ctx context.Context, in repository.DeleteUserInput)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.DeleteUserInput))
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(_a0 error) *MockUserRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context.Context, repository.DeleteUserInput) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, in
func (_m *MockUserRepository) Get(ctx context.Context, in repository.GetUserInput) (*repository.GetUserOutput, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *repository.GetUserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetUserInput) (*repository.GetUserOutput, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.GetUserInput) *repository.GetUserOutput); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.GetUserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.GetUserInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.GetUserInput
func (_e *MockUserRepository_Expecter) Get(ctx interface{}, in interface{}) *MockUserRepository_Get_Call {
	return &MockUserRepository_Get_Call{Call: _e.mock.On("Get", ctx, in)}
}

func (_c *MockUserRepository_Get_Call) Run(run func(ctx context.Context, in repository.GetUserInput)) *MockUserRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.GetUserInput))
	})
	return _c
}

func (_c *MockUserRepository_Get_Call) Return(_a0 *repository.GetUserOutput, _a1 error) *MockUserRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_Get_Call) RunAndReturn(run func(context.Context, repository.GetUserInput) (*repository.GetUserOutput, error)) *MockUserRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*repository.GetUserOutput, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *repository.GetUserOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*repository.GetUserOutput, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *repository.GetUserOutput); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.GetUserOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetByEmail_Call {
	return &MockUserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) Return(_a0 *repository.GetUserOutput, _a1 error) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*repository.GetUserOutput, error)) *MockUserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockUserRepository) List(ctx context.Context, limit int, offset int) (*repository.ListUsersOutput, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repository.ListUsersOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) (*repository.ListUsersOutput, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *repository.ListUsersOutput); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.ListUsersOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUserRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockUserRepository_List_Call {
	return &MockUserRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockUserRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUserRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserRepository_List_Call) Return(_a0 *repository.ListUsersOutput, _a1 error) *MockUserRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_List_Call) RunAndReturn(run func(context.Context, int, int) (*repository.ListUsersOutput, error)) *MockUserRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, in
func (_m *MockUserRepository) Update(ctx context.Context, in repository.UpdateUserInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdateUserInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.UpdateUserInput
func (_e *MockUserRepository_Expecter) Update(ctx interface{}, in interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", ctx, in)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(ctx context.Context, in repository.UpdateUserInput)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.UpdateUserInput))
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(_a0 error) *MockUserRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context.Context, repository.UpdateUserInput) error) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function with given fields: ctx, in
func (_m *MockUserRepository) UpdatePassword(ctx context.Context, in repository.UpdatePasswordInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UpdatePasswordInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserRepository_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.UpdatePasswordInput
func (_e *MockUserRepository_Expecter) UpdatePassword(ctx interface{}, in interface{}) *MockUserRepository_UpdatePassword_Call {
	return &MockUserRepository_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, in)}
}

func (_c *MockUserRepository_UpdatePassword_Call) Run(run func(ctx context.Context, in repository.UpdatePasswordInput)) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.UpdatePasswordInput))
	})
	return _c
}

func (_c *MockUserRepository_UpdatePassword_Call) Return(_a0 error) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdatePassword_Call) RunAndReturn(run func(context.Context, repository.UpdatePasswordInput) error) *MockUserRepository_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// WithExecutor provides a mock function with given fields: exec
func (_m *MockUserRepository) WithExecutor(exec transaction.SqlxTx) repositories.UserRepository {
	ret := _m.Called(exec)

	if len(ret) == 0 {
		panic("no return value specified for WithExecutor")
	}

	var r0 repositories.UserRepository
	if rf, ok := ret.Get(0).(func(transaction.SqlxTx) repositories.UserRepository); ok {
		r0 = rf(exec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repositories.UserRepository)
		}
	}

	return r0
}

// MockUserRepository_WithExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithExecutor'
type MockUserRepository_WithExecutor_Call struct {
	*mock.Call
}

// WithExecutor is a helper method to define mock.On call
//   - exec transaction.SqlxTx
func (_e *MockUserRepository_Expecter) WithExecutor(exec interface{}) *MockUserRepository_WithExecutor_Call {
	return &MockUserRepository_WithExecutor_Call{Call: _e.mock.On("WithExecutor", exec)}
}

func (_c *MockUserRepository_WithExecutor_Call) Run(run func(exec transaction.SqlxTx)) *MockUserRepository_WithExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(transaction.SqlxTx))
	})
	return _c
}

func (_c *MockUserRepository_WithExecutor_Call) Return(_a0 repositories.UserRepository) *MockUserRepository_WithExecutor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_WithExecutor_Call) RunAndReturn(run func(transaction.SqlxTx) repositories.UserRepository) *MockUserRepository_WithExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
