// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/alexbro4u/gotemplate/internal/dto/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockBlacklistRepository is an autogenerated mock type for the BlacklistRepository type
type MockBlacklistRepository struct {
	mock.Mock
}

type MockBlacklistRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlacklistRepository) EXPECT() *MockBlacklistRepository_Expecter {
	return &MockBlacklistRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, in
func (_m *MockBlacklistRepository) Add(ctx context.Context, in repository.AddToBlacklistInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AddToBlacklistInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlacklistRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockBlacklistRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - in repository.AddToBlacklistInput
func (_e *MockBlacklistRepository_Expecter) Add(ctx interface{}, in interface{}) *MockBlacklistRepository_Add_Call {
	return &MockBlacklistRepository_Add_Call{Call: _e.mock.On("Add", ctx, in)}
}

func (_c *MockBlacklistRepository_Add_Call) Run(run func(ctx context.Context, in repository.AddToBlacklistInput)) *MockBlacklistRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.AddToBlacklistInput))
	})
	return _c
}

func (_c *MockBlacklistRepository_Add_Call) Return(_a0 error) *MockBlacklistRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlacklistRepository_Add_Call) RunAndReturn(run func(context.Context, repository.AddToBlacklistInput) error) *MockBlacklistRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *MockBlacklistRepository) DeleteExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlacklistRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockBlacklistRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBlacklistRepository_Expecter) DeleteExpired(ctx interface{}) *MockBlacklistRepository_DeleteExpired_Call {
	return &MockBlacklistRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *MockBlacklistRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *MockBlacklistRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBlacklistRepository_DeleteExpired_Call) Return(_a0 error) *MockBlacklistRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlacklistRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) error) *MockBlacklistRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlacklistRepository creates a new instance of MockBlacklistRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlacklistRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlacklistRepository {
	mock := &MockBlacklistRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
