with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
packages:
  github.com/alexbro4u/gotemplate/internal/layers/repositories:
    config:
      dir: "internal/mocks"
      outpkg: mocks
    interfaces:
      UserRepository:
      UserGroupRepository:
  github.com/alexbro4u/uowkit/uow:
    config:
      dir: "internal/mocks"
      outpkg: mocks
    interfaces:
      UnitOfWork:
